config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:message]
    if @question.include?("?")
      @answer = 'Silly question! Get dressed and go back to work!'
    elsif @question == @question.upcase && @question != 'I am going to work right now!'
      @answer = "I can feel your motivation! I don't care, get dressed and go to work!"
    elsif @question != 'I am going to work right now!'
      @answer = "I don't care, get dressed and go to work!"
    else
      @answer = 'Great! Por fin!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div id="your-question">
<h1>-You</h1>
<p><%= @question %></p>
</div>
<div id="coach-answer">
<h1>-Coach:</h2>
<p><%= @answer %></p>
</div>

app/views/questions/ask.html.erb
<p>Ask your coach anything</p>

<form action="/answer" method="get">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="message" placeholder="Message">
  <input type="submit">
</form>

<% link_to "answer", answer_path %>